"""
ingestion/drone_loader.py

Loads real VLM-processed drone/satellite observation descriptions into LangChain Documents.
These descriptions are generated by ingestion/vlm_processor.py using Ollama LLaVA.

Fix log:
  - REMOVED: generate_mock_drone_descriptions() and import random — synthetic data
    contaminated the RAG database. Removed entirely with no fallback.
  - FIXED: Now raises a clear, actionable error when real data is missing.
  - FIXED: CRLF → LF line endings
"""
import json
import os
from langchain_core.documents import Document


def load_drone_data(json_path: str) -> list[Document]:
    """
    Loads VLM-generated drone/satellite observation documents from a JSON file.
    Each record must have been generated by ingestion/vlm_processor.py using
    Ollama LLaVA (real AI descriptions, NOT synthetic/mock data).

    Args:
        json_path: Path to the real_drone_metadata.json file.

    Returns:
        List of LangChain Document objects for ChromaDB ingestion.

    Raises:
        FileNotFoundError if the JSON file doesn't exist.
    """
    if not os.path.exists(json_path):
        print(
            f"\n  [Drone Loader] Real VLM metadata not found at:\n"
            f"    {json_path}\n\n"
            f"  To generate it:\n"
            f"    1. Extract images: python ingestion/extract_xview2_subset.py\n"
            f"    2. Install Ollama: https://ollama.ai → ollama pull llava\n"
            f"    3. Process images: python ingestion/vlm_processor.py\n\n"
            f"  Skipping imagery_description modality — 0 documents loaded."
        )
        return []

    try:
        with open(json_path, "r", encoding="utf-8") as f:
            records = json.load(f)
    except json.JSONDecodeError as e:
        print(f"  [Drone Loader] JSON parse error in {json_path}: {e}")
        return []

    if not records:
        print(f"  [Drone Loader] WARNING: {json_path} is empty — 0 documents loaded.")
        return []

    documents = []
    for row in records:
        # Support both field name conventions (vlm_processor.py uses 'observations')
        description = row.get("observations") or row.get("vlm_description") or ""
        if not description:
            continue

        image_id  = row.get("drone_id") or row.get("image_id", "unknown")
        location  = row.get("location", "Unknown Location")
        timestamp = row.get("timestamp", "Unknown Time")
        disaster  = row.get("disaster_type", "Unknown")
        src_file  = row.get("source_file", "")

        text = (
            f"DRONE/SATELLITE OBSERVATION [{disaster}] at {location} "
            f"({timestamp}): {description}"
        )
        metadata = {
            "source":        "Drone_VLM",
            "image_id":      image_id,
            "location":      location,
            "modality":      "imagery_description",
            "timestamp":     timestamp,
            "disaster_type": disaster,
            "source_file":   src_file,
        }
        documents.append(Document(page_content=text, metadata=metadata))

    print(f"  [Drone Loader] Loaded {len(documents)} real VLM observation documents.")
    return documents


if __name__ == "__main__":
    path = os.path.join("data", "imagery", "real_drone_metadata.json")
    docs = load_drone_data(path)
    for d in docs[:3]:
        print(d.page_content[:200])
        print()
